shell: /bin/zsh
userCommandsExec:
  - command: make build-and-push
    relativePath: ./
    label: build and push image to homelab registry
    runner: ''
fzfConfig:
  windowHeight: 50%
  previewWindow:
    direction: right
    percentage: 50%
root: /Users/mateuszklusek/vault/portfolio/homelab-auth-service
